# -*- coding: utf-8 -*-
"""summarize PDF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ib6kcshfS0UYyIxBTvshYJYURLJMukZN
"""

!pip install -q gradio openai pypdf tiktoken langchain

import os
from pathlib import Path
import gradio as gr
from langchain import OpenAI, PromptTemplate
from langchain.chains.summarize import load_summarize_chain
from langchain.document_loaders import PyPDFLoader
import tiktoken

# Configuration
OPENAI_API_KEY = "sk-61l36KGFBfmwgTu3jxWwT3BlbkFJw8GB3vh0"
TEMPERATURE = 0
CHAIN_TYPE = "map_reduce"

# Environment Variables
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

def num_tokens_from_string(string: str, encoding_name: str) -> int:
    encoding = tiktoken.get_encoding(encoding_name)
    return len(encoding.encode(string))

def summarize_pdf(pdf_file_path: str) -> str:
    loader = PyPDFLoader(pdf_file_path)
    docs = loader.load_and_split()
    chain = load_summarize_chain(OpenAI(temperature=TEMPERATURE), chain_type=CHAIN_TYPE)
    return chain.run(docs)

def launch_gradio_interface():
    input_pdf_path = gr.components.Textbox(label="PDF path")
    output_summary = gr.components.Textbox(label="Summary")

    interface = gr.Interface(
        fn=summarize_pdf,
        inputs=input_pdf_path,
        outputs=output_summary,
        title="Summarize PDF",
        description="PDF path",
    )

    interface.launch(share=True)

if __name__ == "__main__":
  launch_gradio_interface()